apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: msigmonitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
  type: LoadBalancer
  sessionAffinity: ClientIP