apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis-master
  - port: 26379
    protocol: TCP
    targetPort: 26379
    name: redis-sentinel
  selector:
    app: redis-primary
