apiVersion: v1
kind: Service
metadata:
  name: redis-secondary
  namespace: redis
spec:
  type: NodePort
  ports:
  - port: 26379
    targetPort: 26379
    protocol: TCP
  selector:
    app: redis-secondary

