apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-monitoring-hook-conf
  namespace: msigmonitoring
data:
  fluent.conf: |-
      <source>
        @type tail
        format multiline
        format_firstline /[0-9]{2}-[A-Za-z]{3}-[0-9]{4}/
        format1 /^(?<datetime>[0-9]{2}-[A-Za-z]{3}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}) (?<Log-Level>[A-Z]*) (?<message>.*)$/
        path /opt/logs/*.log
        pos_file /tmp/spring.pos
        tag boot
      </source>
      <match boot>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.elastic-kibana'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      index_name fluentd-monitoring2
      type_name fluentd
      flush_interval 10s
      </match>


